---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pulseops
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: pulseops-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: pulseops
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pulseops-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: pulseops
  namespace: default
